### ISSUE TITLE
Breaks in browsers with canvas fingerprinting protections

### ISSUE THREAD

**Issue by pes10k** [lovasoa/bin2png#11]
Hi!  The approached used in your lib won't work in browsers with canvas fingerprinting protections (like Tor Browser Bundle and Brave).  I was wondering if you might add a note in your readme noting the limitation, so that developers would know about potential compatibility issues (and possibly with a link to https://www.phpied.com/asynchronous-inline-scripts-via-data-urls/ as alternative options)?

I found this when debugging a report here: https://twitter.com/Fdecampredon/status/1366438532173225992

Thanks for the great lib and for your time!

**Comment by lovasoa** [comment]
Inline scripts are not an alternative. The alternative may be to just include the raw data in the page, but you would loose the compression that PNG offers.

**Comment by pes10k** [comment]
i may have described poorly, but my suggestion isn't an inline script, its to

1. Encode (and optionally minify, compress, etc) the JS in a base64 data URL
2. Use that URL in an async script tag

Just to tie the two discussions together: https://github.com/brave/brave-browser/issues/14421

**Comment by pes10k** [comment]
Thank you very much :)

**Comment by lovasoa** [comment]
> i may have described poorly, but my suggestion isn't an inline script, its to [...]

Yes, I got it. But you will have to ship the js decompression code, and the decompression will be synchronous.
